"""empty message

Revision ID: a6f1f789570a
Revises: af8bbbf2124a
Create Date: 2019-01-11 18:11:16.404905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f1f789570a'
down_revision = 'af8bbbf2124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
