"""notebook table

Revision ID: cfffdbad6c9f
Revises: a6f1f789570a
Create Date: 2019-01-18 13:36:11.460480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfffdbad6c9f'
down_revision = 'a6f1f789570a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notes', sa.Column('notebook_id', sa.Integer(), nullable=False))
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'notebooks', ['notebook_id'], ['id'])
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_user_id_fkey', 'notes', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'notebook_id')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
